name: Scheduled Health Check

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *' # at the end of everyday

jobs:
  scheduled_healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://redux-anecdotes-app.herokuapp.com/anecdotes"